version: '3.6'

services:
  web:
    build:
      dockerfile: Dockerfile.prod
    image: quantimage2-frontend_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=prod"
      - "traefik.http.routers.quantimage2-frontend-web.rule=Host(`${TRAEFIK_URL}`)"
    networks:
      - default
      - prod

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}

