export const FEATURE_DEFINITIONS = [
  {
    id: 'firstorder_10Percentile',
    url: 'www.radiomics.org/RO/GPMT',
    description: '10 Percentile of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_90Percentile',
    url: 'www.radiomics.org/RO/OZ0C',
    description: '90 percentile of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Energy',
    url: 'www.radiomics.org/RO/8ZQL',
    description: '',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Entropy',
    url: 'www.radiomics.org/RO/TLU2',
    description: 'It is the Shannon entropy of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_InterquartileRange',
    url: 'www.radiomics.org/RO/WR0O',
    description:
      'Difference between the 75 and 25 interquartiles of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Kurtosis',
    url: 'www.radiomics.org/RO/C3I7',
    description:
      'Kurtosis is a measure of how outlier-prone a distribution is. The kurtosis of the normal distribution is 3. Distributions that are more outlier-prone than the normal distribution have kurtosis greater than 3; distributions that are less outlier-prone have kurtosis less than 3',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Maximum',
    url: 'www.radiomics.org/RO/3NCY',
    description: 'Highest discretized grey level in the histogram distribution',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Mean',
    url: 'www.radiomics.org/RO/X6K6',
    description: 'The mean gray level',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_MeanAbsoluteDeviation',
    url: 'www.radiomics.org/RO/D2ZX',
    description: 'Measure of dispersion from the mean of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Median',
    url: 'www.radiomics.org/RO/WIFQ',
    description: 'Median value of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Minimum',
    url: 'www.radiomics.org/RO/1PR8',
    description: 'Minimum gray level bin',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Range',
    url: 'www.radiomics.org/RO/5Z3W',
    description: 'Difference between maximum and minimum of the histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_RobustMeanAbsoluteDeviation',
    url: 'www.radiomics.org/RO/WRZB',
    description:
      'The intensity histogram robust mean absolute deviation is the mean restricted to grey values closer to the center of the distribution',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_RootMeanSquared',
    url: 'www.radiomics.org/RO/5ZWQ',
    description: '',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Skewness',
    url: 'www.radiomics.org/RO/88K1',
    description:
      'The skewness measures the degree of histogram of gray levels asymmetry around the central value',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_TotalEnergy',
    url: 'www.radiomics.org/RO/2490',
    description:
      'Total Energy is the value of Energy feature scaled by the volume of the voxel in cubic mm',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Uniformity',
    url: 'www.radiomics.org/RO/BJ5W',
    description:
      'The uniformity is a measure of the randomness of the grey levels distribution histogram',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'firstorder_Variance',
    url: 'www.radiomics.org/RO/CH89',
    description: 'Variance of the intensities',
    category: 'Intensity',
    subcategory: '',
  },
  {
    id: 'glcm_Autocorrelation',
    url: 'www.radiomics.org/RO/QWB0',
    description:
      'The autocorrelation compares all possible pixel pairs and reporting the likelihood that both will be bright as a function of the distance and direction of separation',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_ClusterProminence',
    url: 'www.radiomics.org/RO/AE86',
    description:
      'The cluster prominence is a measure of asymmetry. When the cluster prominence value is high, the image is less symmetric',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_ClusterShade',
    url: 'www.radiomics.org/RO/7NFM',
    description:
      'The cluster shade is a measure of the skewness of the matrix and it is believed to gauge the perceptual concepts of uniformity. When the cluster age is high the image is asymmetric',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_ClusterTendency',
    url: 'www.radiomics.org/RO/DG8W',
    description:
      'The cluster tendency indicates into how many clusters the gray levels present in the image can be classified',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Contrast',
    url: 'www.radiomics.org/RO/ACUI',
    description:
      'Contrast assesses grey level variations. It is defines as in https://doi.org/10.5589/m02-004',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Correlation',
    url: 'www.radiomics.org/RO/NI2N',
    description:
      'The correlation feature shows the linear dependence of gray level values in the cooccurence matrix',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_DifferenceAverage',
    url: 'www.radiomics.org/RO/TF7R',
    description: 'The average for the diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_DifferenceEntropy',
    url: 'www.radiomics.org/RO/NTRS',
    description: 'The entropy for the diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_DifferenceVariance',
    url: 'www.radiomics.org/RO/D3YU',
    description: 'The variance for the diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Id',
    url: 'www.radiomics.org/RO/IB1Z',
    description:
      'Inverse difference is a measure of homogeneity. Grey level co-occurrences with a large difference in levels are weighed less, thus lowering the total feature score. The feature score is maximal if all grey levels are the same',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Idm',
    url: 'www.radiomics.org/RO/WF0Z',
    description:
      'Same as the inverse difference feature, but with lower weigths for elements that are further from the diagonal',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Idmn',
    url: 'www.radiomics.org/RO/1QCO',
    description:
      'Normalized version of the inverse difference moment, as suggested by https://doi.org/10.5589/m02-004',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Idn',
    url: 'www.radiomics.org/RO/NDRX',
    description:
      'Normalized inverse difference as suggested in https://doi.org/10.5589/m02-004',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Imc1',
    url: 'www.radiomics.org/RO/R8DG',
    description:
      'The IMC1 is related to the entropy of the images and gives information on how a pixel value is correlated to its neighbourod',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_Imc2',
    url: 'www.radiomics.org/RO/JN9H',
    description: '???',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_InverseVariance',
    url: 'www.radiomics.org/RO/E8JP',
    description:
      'The inverse variance feature measures how the gray tone differences are distributed in pair elements',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_JointAverage',
    url: 'www.radiomics.org/RO/60VM',
    description: 'The grey level weigthed sum of joint probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_JointEnergy',
    url: 'www.radiomics.org/RO/8ZQL',
    description:
      'It represents the energy of the probability matrix. Please note that this feature is also called Energy or Uniformity.',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_JointEntropy',
    url: 'www.radiomics.org/RO/TU9B',
    description: 'As defined in http://dx.doi.org/10.1109/TSMC.1973.4309314',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_MaximumProbability',
    url: 'www.radiomics.org/RO/GYBY',
    description:
      'Probability corresponding to the most common grey level co-occurence in the GCLM',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_MCC',
    url: 'www.radiomics.org/RO/xxx',
    description: '???',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_SumAverage',
    url: 'www.radiomics.org/RO/ZGXS',
    description: 'The average for the cross-diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_SumEntropy',
    url: 'www.radiomics.org/RO/P6QZ',
    description: 'The entropy for the cross-diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'glcm_SumSquares',
    url: 'www.radiomics.org/RO/OEEB',
    description: 'The variance for the cross-diagonal probabilities',
    category: 'Texture',
    subcategory: 'GLCM',
  },
  {
    id: 'gldm_DependenceEntropy',
    url: 'www.radiomics.org/RO/GBDU',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_DependenceNonUniformity',
    url: 'www.radiomics.org/RO/V294',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_DependenceNonUniformityNormalized',
    url: 'www.radiomics.org/RO/IATH',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_DependenceVariance',
    url: 'www.radiomics.org/RO/7WT1',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_GrayLevelNonUniformity',
    url: 'www.radiomics.org/RO/VFT7',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_GrayLevelVariance',
    url: 'www.radiomics.org/RO/QK93',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_HighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/K26C',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_LargeDependenceEmphasis',
    url: 'www.radiomics.org/RO/MB4I',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_LargeDependenceHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/KLTH',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_LargeDependenceLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/A7WM',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_LowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/S1RA',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_SmallDependenceEmphasis',
    url: 'www.radiomics.org/RO/0GBI',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_SmallDependenceHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/DKNJ',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'gldm_SmallDependenceLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/RUVG',
    description: '',
    category: 'Texture',
    subcategory: 'GLDM',
  },
  {
    id: 'glrlm_GrayLevelNonUniformity',
    url: 'www.radiomics.org/RO/R5YN',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_GrayLevelNonUniformityNormalized',
    url: 'www.radiomics.org/RO/OVBL',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_GrayLevelVariance',
    url: 'www.radiomics.org/RO/8CE5',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_HighGrayLevelRunEmphasis',
    url: 'www.radiomics.org/RO/G3QZ',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_LongRunEmphasis',
    url: 'www.radiomics.org/RO/W4KF',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_LongRunHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/3KUM',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_LongRunLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/IVPO',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_LowGrayLevelRunEmphasis',
    url: 'www.radiomics.org/RO/V3SW',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_RunEntropy',
    url: 'www.radiomics.org/RO/HJ9O',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_RunLengthNonUniformity',
    url: 'www.radiomics.org/RO/W92Y',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_RunLengthNonUniformityNormalized',
    url: 'www.radiomics.org/RO/IC23',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_RunPercentage',
    url: 'www.radiomics.org/RO/9ZK5',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_RunVariance',
    url: 'www.radiomics.org/RO/SXLW',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_ShortRunEmphasis',
    url: 'www.radiomics.org/RO/22OV',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_ShortRunHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/GD3A',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glrlm_ShortRunLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/HTZT',
    description: '',
    category: 'Texture',
    subcategory: 'GLRLM',
  },
  {
    id: 'glszm_GrayLevelNonUniformity',
    url: 'www.radiomics.org/RO/JNSA',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_GrayLevelNonUniformityNormalized',
    url: 'www.radiomics.org/RO/Y1RO',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_GrayLevelVariance',
    url: 'www.radiomics.org/RO/BYLV',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_HighGrayLevelZoneEmphasis',
    url: 'www.radiomics.org/RO/5GN9',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_LargeAreaEmphasis',
    url: 'www.radiomics.org/RO/48P8',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_LargeAreaHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/J17V',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_LargeAreaLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/YH51',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_LowGrayLevelZoneEmphasis',
    url: 'www.radiomics.org/RO/XMSY',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_SizeZoneNonUniformity',
    url: 'www.radiomics.org/RO/4JP3',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_SizeZoneNonUniformityNormalized',
    url: 'www.radiomics.org/RO/VB3A',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_SmallAreaEmphasis',
    url: 'www.radiomics.org/RO/5QRC',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_SmallAreaHighGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/HW1V',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_SmallAreaLowGrayLevelEmphasis',
    url: 'www.radiomics.org/RO/5RAI',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_ZoneEntropy',
    url: 'www.radiomics.org/RO/GU8N',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_ZonePercentage',
    url: 'www.radiomics.org/RO/P30P',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'glszm_ZoneVariance',
    url: 'www.radiomics.org/RO/3NSA',
    description: '',
    category: 'Texture',
    subcategory: 'GLSZM',
  },
  {
    id: 'ngtdm_Busyness',
    url: 'www.radiomics.org/RO/NQ30',
    description: '',
    category: 'Texture',
    subcategory: 'NGTDM',
  },
  {
    id: 'ngtdm_Coarseness',
    url: 'www.radiomics.org/RO/QCDE',
    description: '',
    category: 'Texture',
    subcategory: 'NGTDM',
  },
  {
    id: 'ngtdm_Complexity',
    url: 'www.radiomics.org/RO/HDEZ',
    description: '',
    category: 'Texture',
    subcategory: 'NGTDM',
  },
  {
    id: 'ngtdm_Contrast',
    url: 'www.radiomics.org/RO/65HE',
    description: '',
    category: 'Texture',
    subcategory: 'NGTDM',
  },
  {
    id: 'ngtdm_Strength',
    url: 'www.radiomics.org/RO/1X9X',
    description: '',
    category: 'Texture',
    subcategory: 'NGTDM',
  },
  {
    id: 'shape_Maximum3DDiameter',
    url: 'www.radiomics.org/RO/L0JK',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_MeshVolume',
    url: 'www.radiomics.org/RO/RNU0',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_MajorAxisLength',
    url: 'www.radiomics.org/RO/TDIC',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Sphericity',
    url: 'www.radiomics.org/RO/QCFX',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_LeastAxisLength',
    url: 'www.radiomics.org/RO/7J51',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Elongation',
    url: 'www.radiomics.org/RO/Q3CK',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_SurfaceVolumeRatio',
    url: 'www.radiomics.org/RO/2PR5',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Maximum2DDiameterSlice',
    url: 'www.radiomics.org/RO/2130',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Flatness',
    url: 'www.radiomics.org/RO/N17B',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_SurfaceArea',
    url: 'www.radiomics.org/RO/C0JK',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_MinorAxisLength',
    url: 'www.radiomics.org/RO/P9VJ',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Maximum2DDiameterColumn',
    url: 'www.radiomics.org/RO/2150',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_Maximum2DDiameterRow',
    url: 'www.radiomics.org/RO/2140',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
  {
    id: 'shape_VoxelVolume',
    url: 'www.radiomics.org/RO/RNU0',
    description: '',
    category: 'Shape',
    subcategory: '',
  },
];

export const CATEGORY_DEFINITIONS = {
  // Modalities
  CT: 'Computed Tomography',
  PT: 'Positron emission tomography',
  MR: 'Magnetic resonance imaging',
  // Families
  Intensity:
    'Features based on the grey levels of the pixels in the image (maximum, minimum, mean, etc.)',
  SUV:
    'Features based on the grey levels of the pixels in the image (maximum, minimum, mean, etc.)',
  Texture:
    'The textural features describe patterns or the spatial distribution of voxel intensities',
  Shape:
    'Morphological features describe geometric aspects of a region of interest (ROI), such as area and volume. Morphological features are based on ROI voxel representations of the volume.',
  // Sub-families
  GLCM:
    'The grey level co-occurrence matrix (GLCM) is a matrix that expresses how combinations of discretised grey levels of neighbouring pixels, or voxels in a 3D volume, are distributed along one of the image directions. In a 3 dimensional approach to texture analysis, the direct neighbourhood of a voxel consists of the 26 directly neighbouring voxels. Thus, there are 13 unique direction vectors within a neighbourhood volume for distance',
  PET:
    'Features calculated specifically from PET images, concerning properties of a tumor',
};

export const FEATURE_CATEGORY_ALIASES = {
  PT: { Intensity: 'SUV' },
};
